# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchFromGitHub }:

buildGoPackage rec {
  name = "direnv-caascad-${version}";
  version = "2.21.2-cc.2";

  goPackagePath = "github.com/Caascad/direnv";

  src = fetchFromGitHub {
    owner = "Caascad";
    repo = "direnv";
    rev = "${version}";
    sha256 = "1zd1a3wb4w3jaavvjadyqxw3c7ckxdbcvb7vqj79pry8s328fpaf";
  };

  goDeps = ./deps.nix;

  meta = with stdenv.lib; {
      description = "A shell extension that manages your environment";
      longDescription = ''
        Once hooked into your shell direnv is looking for an .envrc file in your
        current directory before every prompt.

        If found it will load the exported environment variables from that bash
        script into your current environment, and unload them if the .envrc is
        not reachable from the current path anymore.

        In short, this little tool allows you to have project-specific
        environment variables.
      '';
      homepage = https://direnv.net;
      license = licenses.mit;
  };
}
