# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/BurntSushi/toml";
    fetch = {
      type = "git";
      url = "https://github.com/BurntSushi/toml";
      rev = "3012a1dbe2e4bd1391d42b32f0577cb7bbc7f005";
      sha256 = "1fjdwwfzyzllgiwydknf1pwjvy49qxfsczqx5gz3y0izs7as99j6";
    };
  }
  {
    goPackagePath = "github.com/direnv/direnv";
    fetch = {
      type = "git";
      url = "https://github.com/direnv/direnv";
      rev = "8b4b2687c9146ac1e315f69e0e372ded582beab3";
      sha256 = "1lqw66cmh1nnqykpakkxczrfql9p19kp54h2nzhbpzk3pv1dmdb8";
    };
  }
  {
    goPackagePath = "github.com/direnv/go-dotenv";
    fetch = {
      type = "git";
      url = "https://github.com/direnv/go-dotenv";
      rev = "4cce6d1a66f7bc8dc730eab85cab6af1b801abed";
      sha256 = "00wn4fc2lma0csf6ryvlc6k9jbpbifm4n7i3kkd2xrfw5qlm29b6";
    };
  }
  {
    goPackagePath = "golang.org/x/mod";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/mod";
      rev = "e5e73c1b9c72835114eb6daab038373d39515006";
      sha256 = "1alh35bz2778gn4bl6rn1lidq9d3xpkbqnbr4k2rnk73pmqkcgxm";
    };
  }
]
